name: Check Markdown links for modified files

on: [pull_request]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:

    - name: Check out Git repository
      uses: actions/checkout@v3
    
    # Workaround for `fatal: unsafe repository (REPO is owned by someone else)` issue
    # https://github.com/actions/checkout/issues/760
    # https://github.com/actions/checkout/issues/766
    # - name: Trust /github/workspace (before git v2.35.2)
    #   run: export GIT_CEILING_DIRECTORIES=/github/workspace

    # - name: Trust /github/workspace (after git v2.35.2)
    #   run: git config --global --add safe.directory /github/workspace

    # https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/132
    - name: Run markdown-link-check
      uses: KATO-Hiro/github-action-markdown-link-check@master
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        check-modified-files-only: 'yes'
        base-branch: 'main'
        folder-path: 'docs'
        file-path: './README.md'
